Repository morning-night-guild/platform-infra, pull requests merged in 2023-02, with the labels that each got.

#35 #34 manifest更新方法を修正
  .github/workflows/cotainer.check.yaml
  .github/workflows/manifest.lint.yaml
  .github/workflows/manifest.update.prod.yaml
  Makefile
  README.md
  charts/platform/.helmignore
  charts/platform/Chart.yaml
  charts/platform/templates/deployment.yaml
  charts/platform/templates/secret/.gitignore
  charts/platform/templates/secret/api-key.yaml
  charts/platform/templates/secret/database-url.yaml
  charts/platform/templates/secret/newrelic-app-name.yaml
  charts/platform/templates/secret/newrelic-license.yaml
  charts/platform/templates/service.yaml
  charts/platform/values.yaml
  okteto/prod.sh
  okteto/sops.sh
  script/decrypt.sh
  script/encrypt.sh
  script/secret.sh
Labels: manifest

#37 #34 deploy発火条件を修正
  .github/workflows/okteto.deploy.yaml
Labels: manifest

#38 #34 不要なmanifestを削除
  k8s/.helmignore
  k8s/Chart.yaml
  k8s/env/prod/values.yaml
  k8s/templates/deployment.yaml
  k8s/templates/secret/.gitignore
  k8s/templates/secret/api-key.yaml
  k8s/templates/secret/database-url.yaml
  k8s/templates/secret/newrelic-app-name.yaml
  k8s/templates/secret/newrelic-license.yaml
  k8s/templates/service.yaml
  k8s/values.yaml
Labels: manifest

#41 #40 app-apiとapp-coreアプリを追加
  charts/app-api/.helmignore
  charts/app-api/Chart.yaml
  charts/app-api/templates/deployment.yaml
  charts/app-api/templates/secret/.gitignore
  charts/app-api/templates/service.yaml
  charts/app-api/values.yaml
  charts/app-core/.helmignore
  charts/app-core/Chart.yaml
  charts/app-core/templates/deployment.yaml
  charts/app-core/templates/secret/.gitignore
  charts/app-core/templates/secret/api-key.yaml
  charts/app-core/templates/secret/database-url.yaml
  charts/app-core/templates/secret/newrelic-app-name.yaml
  charts/app-core/templates/secret/newrelic-license.yaml
  charts/app-core/templates/service.yaml
  charts/app-core/values.yaml
  okteto/prod.sh
Labels: manifest

#43 #40 不要となったplatformを削除
  charts/platform/.helmignore
  charts/platform/Chart.yaml
  charts/platform/templates/deployment.yaml
  charts/platform/templates/secret/.gitignore
  charts/platform/templates/secret/api-key.yaml
  charts/platform/templates/secret/database-url.yaml
  charts/platform/templates/secret/newrelic-app-name.yaml
  charts/platform/templates/secret/newrelic-license.yaml
  charts/platform/templates/service.yaml
  charts/platform/values.yaml
  okteto/prod.sh
Labels: manifest

#47 #46 API_KEYをapp-apiに設定
  charts/app-api/templates/deployment.yaml
  charts/app-api/templates/secret/api-key.yaml
  charts/app-core/templates/deployment.yaml
  charts/app-core/templates/secret/api-key.yaml
  script/encrypt.sh
Labels: manifest

#45 #42 vercelをterraformで管理するよう修正
  .github/workflows/terraform.apply.yaml
  .github/workflows/terraform.plan.yaml
  .github/workflows/terraform.preview.yaml
  terraform/.terraform.lock.hcl
  terraform/main.tf
  terraform/vercel.tf
Labels: terraform

#52 #42 不要なリソースを削除
  .github/workflows/terraform.apply.yaml
  .github/workflows/terraform.plan.yaml
  .github/workflows/terraform.preview.yaml
  README.md
  terraform/.terraform.lock.hcl
  terraform/main.tf
  terraform/vercel.tf
Labels: terraform

#60 #59 okteto contextを使うように修正
  .github/workflows/okteto.deploy.yaml
Labels: release
