Repository morning-night-guild/platform-infra, pull requests merged in 2023-03, with the labels that each got.

#63 #62 aquaのPRをオートマージするジョブを追加
  .github/workflows/pr.auto.merge.yaml
Labels: renovate

#66 #65 CORS許可オリジンを更新
  charts/app-api/values.yaml
Labels: manifest

#67 chore(#65) 不要な/を削除
  charts/app-api/values.yaml
Labels: manifest

#70 #69 secretを別チャートで管理
  .github/workflows/cotainer.check.yaml
  .github/workflows/manifest.update.prod.yaml
  .github/workflows/yaml.lint.yaml
  Makefile
  charts/app-api/templates/secret/api-key.yaml
  charts/app-core/templates/secret/database-url.yaml
  charts/app-core/templates/secret/newrelic-app-name.yaml
  charts/app-core/templates/secret/newrelic-license.yaml
  charts/secret/.helmignore
  charts/secret/Chart.yaml
  charts/secret/templates/.gitignore
  charts/secret/values.yaml
  okteto/prod.sh
  okteto/sops.sh
  secret/decrypt.sh
  secret/encrypt.sh
  secret/env/dev/.gitignore
  secret/env/prev/.gitignore
  secret/env/prod/.gitignore
  secret/env/prod/api-key.yaml
  secret/env/prod/database-url.yaml
  secret/env/prod/newrelic-app-name.yaml
  secret/env/prod/newrelic-license.yaml
  secret/secret.sh
Labels: manifest

#71 #69 不要となったスクリプトを削除
  script/decrypt.sh
  script/encrypt.sh
  script/secret.sh
Labels: manifest

#77 #76 secretの管理方法を修正
  .gitignore
  Makefile
  charts/secret/templates/.gitignore
  charts/secret/templates/api-key.yaml
  charts/secret/templates/cockroach-db-url.yaml
  charts/secret/templates/newrelic-app-name.yaml
  charts/secret/templates/newrelic-license.yaml
  okteto.yaml
  okteto/helm.sh
  okteto/sops.sh
  script/decrypt.sh
  script/encrypt.sh
  script/secret.sh
  script/sops.sh
Labels: manifest

#78 [WIP] #76 platform-prodではなくplatformへと変更
  .github/workflows/manifest.update.yaml
  .github/workflows/terraform.apply.yaml
  .github/workflows/terraform.lint.yaml
  .github/workflows/terraform.plan.yaml
  .github/workflows/terraform.preview.yaml
  Makefile
  secret/decrypt.sh
  secret/encrypt.sh
  secret/env/dev/.gitignore
  secret/env/prev/.gitignore
  secret/env/prod/.gitignore
  secret/env/prod/api-key.yaml
  secret/env/prod/cockroach-db-url.yaml
  secret/env/prod/newrelic-app-name.yaml
  secret/env/prod/newrelic-license.yaml
  secret/secret.sh
  terraform/.gitignore
  terraform/backend.tf
  terraform/cockroach.tf
  terraform/valiables.tf
Labels: terraform

#79 #76 cockroach-db-urlを更新
  charts/secret/templates/cockroach-db-url.yaml
Labels: manifest

#81 #80 YugabyteDBを構築
  .github/workflows/terraform.apply.yaml
  .github/workflows/terraform.plan.yaml
  terraform/.terraform.lock.hcl
  terraform/cockroach.tf
  terraform/main.tf
  terraform/yugabyte.tf
Labels: terraform

#82 #80 db-backup cronジョブを追加
  charts/database/templates/cronjob.yaml
  charts/secret/templates/yugabyte-db-url.yaml
Labels: manifest

#85 #84 primaryのデータベースをYugabyteDBに変更
  charts/app-core/templates/deployment.yaml
  charts/database/templates/cronjob.yaml
  charts/database/templates/job.yaml
Labels: manifest
